### ISSUE TITLE
Add endToEndId property to TransactionData

### ISSUE THREAD

**Issue by tolik505** [Dhi13man/nordigen_integration#10]
Hi Dhiman!

There is a property which is missing in `TransactionData` class but is present in the API - `endToEndId ` (https://nordigen.com/en/docs/account-information/output/transactions/). The property is very important since some institutions don't provide `transactionId` but provide `endToEndId ` instead.

It would be really great to add it to `TransactionData` class.

**Comment by Dhi13man** [comment]
Deploying changes in new version.

**Comment by Dhi13man** [comment]
These changes are published in v1.7.6 on [pub.dev](https://pub.dev/packages/nordigen_integration). Thank you for your contribution!

**Comment by tolik505** [comment]
Great! Thank you!
